CREATE DATABASE pethome_raffle;

CREATE TABLE users (
 id SERIAL PRIMARY KEY NOT NULL, 
 name VARCHAR(100) NOT NULL,
 "identificationCard" VARCHAR(11) NOT NULL,
 code INTEGER NOT NULL UNIQUE,
 winner INTEGER NOT NULL DEFAULT 0,
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

create table auth (
 id SERIAL PRIMARY KEY NOT NULL, 
 username VARCHAR(100) NOT NULL UNIQUE,
 password VARCHAR(100) NOT NULL
);
